"""empty message

Revision ID: ca3adb78372e
Revises: 
Create Date: 2024-06-03 22:05:39.073257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca3adb78372e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ficha',
    sa.Column('id_ficha', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=18), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('rua', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_ficha'),
    sa.UniqueConstraint('documento')
    )
    op.drop_table('pedidos')
    op.drop_table('produtomateriaprima')
    op.drop_table('item')
    op.drop_table('estoqueproduto')
    op.drop_table('tamanho')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=15),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('estoquemateriaprima', schema=None) as batch_op:
        batch_op.alter_column('materiaprima',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantidade',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=50),
               nullable=False)
        batch_op.alter_column('data_validade',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=10),
               nullable=False)

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=15),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=50),
               existing_nullable=False)

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=15),
               existing_nullable=True)

    with op.batch_alter_table('estoquemateriaprima', schema=None) as batch_op:
        batch_op.alter_column('data_validade',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=10),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=50),
               nullable=True)
        batch_op.alter_column('quantidade',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('materiaprima',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb3_bin', length=15),
               existing_nullable=True)

    op.create_table('tamanho',
    sa.Column('id_tamanho', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tamanho', mysql.VARCHAR(collation='utf8mb3_bin', length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tamanho'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('estoqueproduto',
    sa.Column('id_item', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tamanho', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_item'], ['item.id_item'], name='estoqueproduto_ibfk_1'),
    sa.ForeignKeyConstraint(['tamanho'], ['tamanho.id_tamanho'], name='estoqueproduto_ibfk_2'),
    sa.PrimaryKeyConstraint('id_item', 'tamanho'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('item',
    sa.Column('id_item', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referencia', mysql.VARCHAR(collation='utf8mb3_bin', length=50), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_item'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('produtomateriaprima',
    sa.Column('id_item', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_materiaprima', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id_item'], ['item.id_item'], name='produtomateriaprima_ibfk_1'),
    sa.ForeignKeyConstraint(['id_materiaprima'], ['materiaprima.id_materiaprima'], name='produtomateriaprima_ibfk_2'),
    sa.PrimaryKeyConstraint('id_item', 'id_materiaprima'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_item', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tamanho', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='pedidos_ibfk_1'),
    sa.ForeignKeyConstraint(['id_item'], ['item.id_item'], name='pedidos_ibfk_2'),
    sa.ForeignKeyConstraint(['tamanho'], ['tamanho.id_tamanho'], name='pedidos_ibfk_3'),
    sa.PrimaryKeyConstraint('id_pedido'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('ficha')
    # ### end Alembic commands ###
